# IAM Service ID scoped to this project — non-human identity for GitHub Actions.
resource "ibm_iam_service_id" "github_actions" {
  name        = "vibebobbing-github-actions"
  description = "Service ID used by GitHub Actions to access VibeBobbing IBM Cloud resources."
}

# IAM policy: Manager role on the Cloudant instance.
# Manager is required because the app creates databases at runtime.
resource "ibm_iam_service_policy" "cloudant_manager" {
  # iam_service_id is deprecated since provider 1.82.0 — use iam_id instead
  iam_id = ibm_iam_service_id.github_actions.iam_id

  roles = ["Manager"]

  resources {
    service              = "cloudantnosqldb"
    resource_instance_id = ibm_resource_instance.cloudant.guid
  }
}

# API key for the service ID — value is sensitive and never logged.
resource "ibm_iam_service_api_key" "github_actions" {
  name           = "vibebobbing-github-actions-key"
  iam_service_id = ibm_iam_service_id.github_actions.iam_id
  description    = "VibeBobbing GitHub Actions — auto-generated by OpenTofu"
}
